src/Entity/OpeningHours.php
<?php

namespace App\Entity;

use App\Repository\OpeningHoursRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: OpeningHoursRepository::class)]
class OpeningHours
{
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique:true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?string $id = null;

    #[ORM\Column(length: 20, unique: true)]
    private ?string $day_of_week = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $opening_time = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $closing_time = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $start_break_time = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $end_of_break = null;

    #[ORM\ManyToOne(inversedBy: 'schedules')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $scheduler = null;

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getDayOfWeek(): ?string
    {
        return $this->day_of_week;
    }

    public function setDayOfWeek(string $day): static
    {
        $this->day_of_week = $day;

        return $this;
    }

    public function getOpeningTime(): ?\DateTimeInterface
    {
        return $this->opening_time;
    }

    public function setOpeningTime(\DateTimeInterface $opening_time): static
    {
        $this->opening_time = $opening_time;

        return $this;
    }

    public function getClosingTime(): ?\DateTimeInterface
    {
        return $this->closing_time;
    }

    public function setClosingTime(\DateTimeInterface $closing_time): static
    {
        $this->closing_time = $closing_time;

        return $this;
    }

    public function getStartBreakTime(): ?\DateTimeInterface
    {
        return $this->start_break_time;
    }

    public function setStartBreakTime(\DateTimeInterface $start_break_time): static
    {
        $this->start_break_time = $start_break_time;

        return $this;
    }

    public function getEndOfBreak(): ?\DateTimeInterface
    {
        return $this->end_of_break;
    }

    public function setEndOfBreak(\DateTimeInterface $end_of_break): static
    {
        $this->end_of_break = $end_of_break;

        return $this;
    }

    public function getScheduler(): ?User
    {
        return $this->scheduler;
    }

    public function setScheduler(?User $scheduler): static
    {
        $this->scheduler = $scheduler;

        return $this;
    }
}

src/Form/OpeningHoursType.php
<?php

namespace App\Form;

use App\Entity\OpeningHours;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OpeningHoursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('day_of_week', ChoiceType::class, [
                'choices' => [
                    'Lundi' => 'Lundi',
                    'Mardi' => 'Mardi',
                    'Mercredi' => 'Mercredi',
                    'Jeudi' => 'Jeudi', 
                    'Vendredi' => 'Vendredi',
                    'Samedi' => 'Samedi',
                    'Dimanche' => 'Dimanche'
                ],
            ])
            ->add('opening_time', TimeType::class)
            ->add('closing_time', TimeType::class)
            ->add('start_break_time', TimeType::class, ['label' => 'Start break time',])
            ->add('end_of_break', TimeType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => OpeningHours::class,
        ]);
    }
}

src/Controller/OpeningHoursController.php
<?php

namespace App\Controller;

use App\Entity\OpeningHours;
use App\Form\OpeningHoursType;
use App\Repository\OpeningHoursRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/opening/hours')]
class OpeningHoursController extends AbstractController
{
    #[Route('/', name: 'app_opening_hours_index', methods: ['GET'])]
    public function index(OpeningHoursRepository $openingHoursRepository): Response
    {
        return $this->render('opening_hours/index.html.twig', [
            'opening_hours' => $openingHoursRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_opening_hours_new', methods: ['GET', 'POST'])]
    public function new(Request $request, OpeningHoursRepository $openingRepo): Response
    {
        $openingHour = new OpeningHours();
        $openingHour->setScheduler($this->getUser());
        $form = $this->createForm(OpeningHoursType::class, $openingHour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $openingRepo->save($openingHour, true);

            return $this->redirectToRoute('app_opening_hours_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('opening_hours/new.html.twig', [
            'opening_hour' => $openingHour,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_opening_hours_show', methods: ['GET'])]
    public function show(OpeningHours $openingHour): Response
    {
        return $this->render('opening_hours/show.html.twig', [
            'opening_hour' => $openingHour,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_opening_hours_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, OpeningHours $openingHour, OpeningHoursRepository $openingRepo): Response
    {
        $form = $this->createForm(OpeningHoursType::class, $openingHour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $openingRepo->save($openingHour, true);

            return $this->redirectToRoute('app_opening_hours_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('opening_hours/edit.html.twig', [
            'opening_hour' => $openingHour,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_opening_hours_delete', methods: ['POST'])]
    public function delete(Request $request, OpeningHours $openingHour, OpeningHoursRepository $openingRepo): Response
    {
        if ($this->isCsrfTokenValid('delete'.$openingHour->getId(), $request->request->get('_token'))) {
            $openingRepo->remove($openingHour, true);

        }

        return $this->redirectToRoute('app_opening_hours_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/opening_hours/_delete_form.html.twig
<form method="post" action="{{ path('app_opening_hours_delete', {'id': opening_hour.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ opening_hour.id) }}">
    <button class="btn">Delete</button>
</form>

templates/opening_hours/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/opening_hours/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit OpeningHours{% endblock %}

{% block body %}
    <h1>Edit OpeningHours</h1>

    {{ include('opening_hours/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_opening_hours_index') }}">back to list</a>

    {{ include('opening_hours/_delete_form.html.twig') }}
{% endblock %}

templates/opening_hours/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}OpeningHours index{% endblock %}

{% block body %}
    <h1>OpeningHours index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Day_of_week</th>
                <th>Opening_time</th>
                <th>Closing_time</th>
                <th>Start_break_time</th>
                <th>End_of_break</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for opening_hour in opening_hours %}
            <tr>
                <td>{{ opening_hour.id }}</td>
                <td>{{ opening_hour.dayOfWeek }}</td>
                <td>{{ opening_hour.openingTime ? opening_hour.openingTime|date('H:i:s') : '' }}</td>
                <td>{{ opening_hour.closingTime ? opening_hour.closingTime|date('H:i:s') : '' }}</td>
                <td>{{ opening_hour.startBreakTime ? opening_hour.startBreakTime|date('H:i:s') : '' }}</td>
                <td>{{ opening_hour.endOfBreak ? opening_hour.endOfBreak|date('H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_opening_hours_show', {'id': opening_hour.id}) }}">show</a>
                    <a href="{{ path('app_opening_hours_edit', {'id': opening_hour.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_opening_hours_new') }}">Create new</a>
{% endblock %}

templates/opening_hours/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New OpeningHours{% endblock %}

{% block body %}
    <h1>Create new OpeningHours</h1>

    {{ include('opening_hours/_form.html.twig') }}

    <a href="{{ path('app_opening_hours_index') }}">back to list</a>
{% endblock %}

templates/opening_hours/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}OpeningHours
{% endblock %}

{% block body %}
	<h1>OpeningHours</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ opening_hour.id }}</td>
			</tr>
			<tr>
				<th>Day_of_week</th>
				<td>{{ opening_hour.dayOfWeek }}</td>
			</tr>
			<tr>
				<th>Opening_time</th>
				<td>{{ opening_hour.openingTime ? opening_hour.openingTime|date('H:i:s') : '' }}</td>
			</tr>
			<tr>
				<th>Closing_time</th>
				<td>{{ opening_hour.closingTime ? opening_hour.closingTime|date('H:i:s') : '' }}</td>
			</tr>
			<tr>
				<th>Start_break_time</th>
				<td>{{ opening_hour.startBreakTime ? opening_hour.startBreakTime|date('H:i:s') : '' }}</td>
			</tr>
			<tr>
				<th>End_of_break</th>
				<td>{{ opening_hour.endOfBreak ? opening_hour.endOfBreak|date('H:i:s') : '' }}</td>
			</tr>
			<tr>
				<th>scheduler</th>
				<td>{{ opening_hour.scheduler }}</td>
			</tr>
		</tbody>
	</table>

	<a href="{{ path('app_opening_hours_index') }}">back to list</a>

	<a href="{{ path('app_opening_hours_edit', {'id': opening_hour.id}) }}">edit</a>

	{{ include('opening_hours/_delete_form.html.twig') }}
{% endblock %}