src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CarRepository::class)]
class Car
{
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique:true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?string $id = null;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank(message: "Veuiller entrer une valeur s'il vous plaît")]
    #[Assert\Length(min:3, minMessage:"Le nom de marquage doit faire plus de {{ limit }} caratères")]
    private ?string $name = null;

    #[ORM\Column(type: Types::JSON)]
    private array $images = [];

    #[ORM\Column]
    #[Assert\NotBlank(message: "Veuiller entrer une valeur s'il vous plaît")]
    #[Assert\Positive(message: "Le prix doit être supérieur à 0")]
    private ?int $price = null;

    #[ORM\Column(nullable: true)]
    private ?string $fiscal_power = null;

    #[ORM\Column()]
    private ?string $engine_power = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $euro_standard = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $crit_air = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $combined_consumption = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $co2_emission = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $posted_at = null;

    #[ORM\ManyToOne(inversedBy: 'posted_cars')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $poster = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Model $model = null;

    #[ORM\OneToOne(mappedBy: 'related_car', cascade: ['persist', 'remove'])]
    private ?CarCaracteristic $characteristics = null;

    #[ORM\OneToOne(mappedBy: 'related_car', cascade: ['persist', 'remove'])]
    private ?EquipmentOptions $equipmentOptions = null;

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getImages(): array
    {
        return $this->images;
    }

    public function setImages(array $images): static
    {
        $this->images = $images;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getFiscalPower(): ?string
    {
        return $this->fiscal_power;
    }

    public function setFiscalPower(?string $fiscal_power): static
    {
        $this->fiscal_power = $fiscal_power;

        return $this;
    }

    public function getEnginePower(): ?string
    {
        return $this->engine_power;
    }

    public function setEnginePower(string $engine_power): static
    {
        $this->engine_power = $engine_power;

        return $this;
    }

    public function getEuroStandard(): ?string
    {
        return $this->euro_standard;
    }

    public function setEuroStandard(?string $euro_standard): static
    {
        $this->euro_standard = $euro_standard;

        return $this;
    }

    public function getCritAir(): ?string
    {
        return $this->crit_air;
    }

    public function setCritAir(?string $crit_air): static
    {
        $this->crit_air = $crit_air;

        return $this;
    }

    public function getCombinedConsumption(): ?string
    {
        return $this->combined_consumption;
    }

    public function setCombinedConsumption(?string $combined_consumption): static
    {
        $this->combined_consumption = $combined_consumption;

        return $this;
    }

    public function getCo2Emission(): ?string
    {
        return $this->co2_emission;
    }

    public function setCo2Emission(?string $co2_emission): static
    {
        $this->co2_emission = $co2_emission;

        return $this;
    }

    public function getPostedAt(): ?\DateTimeInterface
    {
        return $this->posted_at;
    }

    public function setPostedAt(\DateTimeInterface $posted_at): static
    {
        $this->posted_at = $posted_at;

        return $this;
    }

    public function getPoster(): ?User
    {
        return $this->poster;
    }

    public function setPoster(?User $poster): static
    {
        $this->poster = $poster;

        return $this;
    }

    public function getModel(): ?Model
    {
        return $this->model;
    }

    public function setModel(?Model $model): static
    {
        $this->model = $model;

        return $this;
    }

    public function getCharacteristics(): ?CarCaracteristic
    {
        return $this->characteristics;
    }

    public function setCharacteristics(CarCaracteristic $characteristics): static
    {
        // set the owning side of the relation if necessary
        if ($characteristics->getRelatedCar() !== $this) {
            $characteristics->setRelatedCar($this);
        }

        $this->characteristics = $characteristics;

        return $this;
    }

    public function getEquipmentOptions(): ?EquipmentOptions
    {
        return $this->equipmentOptions;
    }

    public function setEquipmentOptions(EquipmentOptions $equipmentOptions): static
    {
        // set the owning side of the relation if necessary
        if ($equipmentOptions->getRelatedCar() !== $this) {
            $equipmentOptions->setRelatedCar($this);
        }

        $this->equipmentOptions = $equipmentOptions;

        return $this;
    }

    public function __toString()
    {
        return $this->model->getBrand().' '.$this->model;
    }
    public function getFileName():string
    {
        return strtolower( preg_replace('/[^\w]*\s*/', '', $this->getName() ));
    }
}

src/Form/CarType.php
<?php

namespace App\Form;

use App\Entity\Car;
use App\Entity\Model;
use DateTime;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'attr' => ['placeholder' => 'FIAT 500 II 1.4 16V 100 LOUNGE']
            ])
            ->add('imageFiles', FileType::class, [
                'multiple' => true,
                'mapped' => false,
                'required' => false,
            ])
            ->add('serie', TextType::class, [
                'label' => 'Numéro de série',
                'required' => false,
                'mapped' => false,
            ])
            ->add('price')
            ->add('fiscal_power')
            ->add('engine_power')
            ->add('euro_standard')
            ->add('crit_air')
            ->add('combined_consumption')
            ->add('co2_emission')
            ->add('model', EntityType::class, [
                'class' => Model::class,
                'choice_label' => 'name',
                'group_by' => 'brand'
            ])
            ->add('characteristics', CarCaracteristicType::class)
            ->add('equipmentOptions', EquipmentOptionsType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Car::class,
        ]);
    }
}

src/Controller/CarController.php
<?php

namespace App\Controller;

use App\Entity\Car;
use App\Entity\CarCaracteristic;
use App\Form\CarType;
use App\Form\FilterType;
use App\Repository\CarCaracteristicRepository;
use App\Repository\CarRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Validator\Constraints\Length;

#[Route('/car')]
class CarController extends AbstractController
{
    #[Route('/', name: 'app_car_index', methods: ['GET', 'POST'])]
    public function index(Request $request, CarRepository $carRepository): Response
    {
        $form = $this->createForm(FilterType::class, null, [
            'action' => $this->generateUrl('app_car_filter', [], UrlGeneratorInterface::ABSOLUTE_URL),
            'validation_groups' => ['Default', 'new'],
        ]);
        $form->handleRequest($request);
        if($request->getContent() != null || $request->getContent() != ''){
            $formData = json_decode($request->getContent());
            $formData = $formData->formData;
            // throw new Exception("Contenue de la requête: ".$request->getContent());
            if(isset($formData->brands)){
                $cars = $carRepository->findByFilter($formData);
                // throw new Exception('Voitures retrouver: '.implode(',',$cars));
                return $this->render('car/index.html.twig', [
                    'cars' => $cars,
                    'form' => $form->createView(),
                ]);
            }
            $this->addFlash('Filtered', 'Liste de voitures filtrées');
        }  
            
        return $this->render('car/index.html.twig', [
            'cars' => $carRepository->findAll(),
            'form' => $form->createView(),
        ]);
    }
    #[Route('/filtered', name: 'app_car_filter', methods: ['POST'])]
    public function filter(Request $request, CarRepository $carRepository, CarCaracteristicRepository $caracteristicRepo): Response
    {
        $form = $this->createForm(FilterType::class);

        $form->handleRequest($request);
        return $this->render('car/filter.html.twig', [ 'form' => $form->createView()]);
    }
    public function saveImage(array $imageFiles, string $brand, string $photoDir, string $filename, string $serie='' ) : array{
        $carImages = [];
        if ($imageFiles) {
            $fileIndex = 0;
            $serie = $serie != '' ? $serie.'_' : $serie;
            foreach ($imageFiles as $key => $imageFile) {
                $finalFileName = $filename.'_'.$serie.''.($fileIndex++).preg_replace('/.+\/+/','', $imageFile->getClientMimeType());
                $imageFile->move($photoDir.'/Vehicles/'.$brand.'/', $finalFileName);
                $carImages[] = $finalFileName;
            }
        }
        return $carImages;
    }

    #[IsGranted('ROLE_EMPLOYE')]
    #[Route('/new', name: 'app_car_new', methods: ['GET', 'POST'])]
    public function new(Request $request,  #[Autowire('%photo_dir%')] string $photoDir, CarRepository $carRepo): Response
    {
        $car = new Car();
        $form = $this->createForm(CarType::class, $car);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // dd($form['imageFiles']->getData());
            $serie = $form['serie']->getData()!=null ? $form['serie']->getData() : '';
            $car->setImages(
                            $this->saveImage($form['imageFiles']->getData(), $car->getModel()->getBrand(),
                            $photoDir, $car->getFileName(), $serie)
            );
            $car->setPostedAt(new DateTime());
            $car->setPoster($this->getUser());

            $carRepo->save($car,true);

            return $this->redirectToRoute('app_car_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('car/new.html.twig', [
            'car' => $car,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_car_show', methods: ['GET'])]
    public function show(Car $car): Response
    {
        return $this->render('car/show.html.twig', [
            'car' => $car,
        ]);
    }

    #[IsGranted('ROLE_EMPLOYE')]
    #[Route('/{id}/edit', name: 'app_car_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Car $car, CarRepository $carRepo): Response
    {
        $form = $this->createForm(CarType::class, $car);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $carRepo->save($car,true);

            return $this->redirectToRoute('app_car_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('car/edit.html.twig', [
            'car' => $car,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_EMPLOYE')]
    #[Route('/{id}', name: 'app_car_delete', methods: ['POST'])]
    public function delete(Request $request, Car $car, CarRepository $carRepo): Response
    {
        if ($this->isCsrfTokenValid('delete'.$car->getId(), $request->request->get('_token'))) {
            $carRepo->remove($car,true);
        }

        return $this->redirectToRoute('app_car_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/car/_delete_form.html.twig
<form method="post" action="{{ path('app_car_delete', {'id': car.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ car.id) }}">
    <button class="btn">Delete</button>
</form>

templates/car/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/car/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Car{% endblock %}

{% block body %}
    <h1>Edit Car</h1>

    {{ include('car/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_car_index') }}">back to list</a>

    {{ include('car/_delete_form.html.twig') }}
{% endblock %}

templates/car/filter.html.twig
<div class="row" id="filter">
	{{ form_start(form) }}
	<div class="col-12 my-1">
		<div class="dropdown" id="brands-dropdown">
			<input type="text" class="form-control" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false" placeholder="Marque">
			<ul class="dropdown-menu" id="brands-input">
				{% for child in form.brands %}
					<li>{{ form_label(child) }}
						{{ form_widget(child) }}</li>
				{% endfor %}
			</ul>
		</div>
		{# {{form_row(form.brands)}} #}
	</div>
	<div class="col-12 my-1" id='filter-models'>
		<div class="dropdown" id="models-dropdown">
			<input type="text" class="form-control" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false" placeholder="Models">
			<ul class="dropdown-menu" id="models-input">
				{% for child in form.models %}
					<li>{{ form_label(child) }}
						{{ form_widget(child) }}</li>
				{% endfor %}
			</ul>
		</div>
		{% if form.manyBrands is defined %}
			{{form_row(form.manyBrands)}}
		{% endif %}

	</div>
	<div class="col-12 my-1">
		<h5>Année de mise en Circulation</h5>
		{{ form_widget(form.minYear, {'attr':{'class':'my-1'}})}}
		{{ form_widget(form.maxYear, {'attr':{'class':'my-1'}})}}
	</div>
	<div class="col-12 my-1" id="energies-input">
		{{form_row(form.energy)}}
	</div>
	<div class="col-12 my-1">
		{{form_row(form.gearbox)}}
	</div>
	<div class="col-12 my-1">
		<h5>Prix</h5>
		{{ form_widget(form.minPrice, {'attr':{'class':'my-1'}})}}
		{{ form_widget(form.maxPrice, {'attr':{'class':'my-1'}})}}
	</div>
	<button class="btn">{{ button_label|default('Rechercher') }}</button>
	{{ form_end(form) }}
</div>

templates/car/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Car index
{% endblock %}

{% block body %}
	<h1>{{ "Nos Voitures d'occasion" |upper }}</h1>

	<div class="row">
		<div class="col-2 my-2">{% include "car/filter.html.twig" %}</div>
		<div class="col-10" id="cars-container">
			<div class=" row row-cols-1 row-cols-md-3 g-4">
				{% for car in cars %}
					<div class="col">
						<div class="card h-100">
							<img src={{ '/Images/Vehicles/'~car.model.brand~'/'~car.images[0:1]|join}} class="card-img-top" alt="...">
							<div class="card-body">
								<h5 class="card-title">{{car}}</h5>
								<h4>{{ car.price ~ '€' }}</h4>
							</div>
							<div class="card-footer d-flex justify-content-between">
								{% if is_granted('ROLE_EMPLOYE') %}
									<a href="{{ path('app_car_edit', {'id': car.id })}}" class="btn btn-primary">Modifier</a>
								{% endif %}
								<a href="{{ path('app_car_show', {'id': car.id })}}" class="btn btn-primary">Détails</a>
								<a href="{{ path('app_car_edit', {'id': car.id })}}" class="btn btn-primary">Contact</a>
							</div>
						</div>
					</div>
				{% else %}
					<div class="alert alert-danger">no records found</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div></div><a href="{{ path('app_car_new') }}">Create new</a>{% endblock %}

templates/car/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Car{% endblock %}

{% block body %}
    <h1>Create new Car</h1>

    {{ include('car/_form.html.twig') }}

    <a href="{{ path('app_car_index') }}">back to list</a>
{% endblock %}

templates/car/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Car{% endblock %}

{% block body %}
    <h1>Car</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ car.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ car.name }}</td>
            </tr>
            <tr>
                <th>Images</th>
                <td>{{ car.images ? car.images|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ car.price }}</td>
            </tr>
            <tr>
                <th>Fiscal_power</th>
                <td>{{ car.fiscalPower }}</td>
            </tr>
            <tr>
                <th>Engine_power</th>
                <td>{{ car.enginePower }}</td>
            </tr>
            <tr>
                <th>Euro_standard</th>
                <td>{{ car.euroStandard }}</td>
            </tr>
            <tr>
                <th>Crit_air</th>
                <td>{{ car.critAir }}</td>
            </tr>
            <tr>
                <th>Combined_consumption</th>
                <td>{{ car.combinedConsumption }}</td>
            </tr>
            <tr>
                <th>Co2_emission</th>
                <td>{{ car.co2Emission }}</td>
            </tr>
            <tr>
                <th>Posted_at</th>
                <td>{{ car.postedAt ? car.postedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_car_index') }}">back to list</a>

    <a href="{{ path('app_car_edit', {'id': car.id}) }}">edit</a>

    {{ include('car/_delete_form.html.twig') }}
{% endblock %}