src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ContactRepository::class)]
class Contact
{
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique:true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?string $id = null;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank(message: "Veuiller entrer une valeur s'il vous plaît")]
    #[Assert\Length(min:3, minMessage:"Le nom de marquage doit faire plus de {{ limit }} caratères")]
    #[Assert\Regex('/[^[:punct:]]/', match: true, message:"Pour les nom composés veuillez les collés avec majuscule")]
    private ?string $sender_firstname = null;

    #[ORM\Column(length: 20)]
    #[Assert\NotBlank(message: "Veuiller entrer une valeur s'il vous plaît")]
    #[Assert\Length(min:3, minMessage:"Le nom de marquage doit faire plus de {{ limit }} caratères")]
    #[Assert\Regex('/[^[:punct:]]/', match: true, message:"Pour les nom composés veuillez les collés avec majuscule")]
    private ?string $sender_lastname = null;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank(message: "Veuiller entrer une valeur s'il vous plaît")]
    #[Assert\Email(mode: "strict")]
    private ?string $sender_email = null;

    #[ORM\Column(length: 255)]
    private ?string $subject = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank(message: "Veuiller entrer une valeur s'il vous plaît")]
    #[Assert\Length(min:3, minMessage:"Le nom de marquage doit faire plus de {{ limit }} caratères")]
    #[Assert\NoSuspiciousCharacters()]
    private ?string $message = null;

    #[ORM\ManyToOne(inversedBy: 'contacts', cascade:['persist'])]
    private ?Client $client = null;

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getSenderFirstname(): ?string
    {
        return $this->sender_firstname;
    }

    public function setSenderFirstname(string $sender_firstname): static
    {
        $this->sender_firstname = $sender_firstname;

        return $this;
    }

    public function getSenderLastname(): ?string
    {
        return $this->sender_lastname;
    }

    public function setSenderLastname(string $sender_lastname): static
    {
        $this->sender_lastname = $sender_lastname;

        return $this;
    }

    public function getSenderEmail(): ?string
    {
        return $this->sender_email;
    }

    public function setSenderEmail(string $sender_email): static
    {
        $this->sender_email = $sender_email;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(string $subject): static
    {
        $this->subject = $subject;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): static
    {
        $this->client = $client;

        return $this;
    }
}

src/Form/ContactType.php
<?php

namespace App\Form;

use App\Entity\Contact;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('sender_firstname')
            ->add('sender_lastname')
            ->add('sender_email', EmailType::class)
            ->add('subject')
            ->add('message', TextareaType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Contact::class,
        ]);
    }
}

src/Controller/ContactController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Entity\Contact;
use App\Form\ContactType;
use App\Repository\ClientRepository;
use App\Repository\ContactRepository;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/contact')]
class ContactController extends AbstractController
{
    #[IsGranted('ROLE_EMPLOYE')]
    #[Route('/', name: 'app_contact_index', methods: ['GET'])]
    public function index(ContactRepository $contactRepository): Response
    {
        return $this->render('contact/index.html.twig', [
            'contacts' => $contactRepository->findAll(),
        ]);
    }
    public function createClient($form, $client, ClientRepository $clientRepo)
    {
        $client = new Client();
        $client->setFirstname($form['sender_firstname']->getData());
        $client->setLastname($form['sender_lastname']->getData());
        $client->setEmail($form['sender_email']->getData());
        $clientRepo->save($client, true);
        return $client;
    }
    #[Route('/new', name: 'app_contact_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ContactRepository $contactRepo, ClientRepository $clientRepo, MailerInterface $mailer): Response
    {
        $contact = new Contact();
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $client = $clientRepo->findOneBy(['email' => $form['sender_email']->getData()]);
            $client = $client == null ? $this->createClient($form, $client, $clientRepo) : $client;
            $contact->setClient($client);
            $contactRepo->save($contact, true);
            $this->mail($mailer, $contact->getSenderEmail());
            // $client->addContact($contact);

            return $this->redirectToRoute('app_contact_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('contact/new.html.twig', [
            'contact' => $contact,
            'form' => $form,
        ]);
    }
    public function mail($mailer, $senderMail){
        $email = (new Email())
            ->from('delofongetsongaetan@gmail.com')
            ->to($senderMail)
            //->cc('cc@example.com')
            //->bcc('bcc@example.com')
            //->replyTo('fabien@example.com')
            //->priority(Email::PRIORITY_HIGH)
            ->subject('Time for Symfony Mailer!')
            ->text('Nouveau contact enregistré')
            ->html('<p>See Twig integration for better HTML integration!</p>');

        $mailer->send($email);
    }

    #[IsGranted('ROLE_EMPLOYE')]
    #[Route('/{id}', name: 'app_contact_show', methods: ['GET'])]
    public function show(Contact $contact): Response
    {
        return $this->render('contact/show.html.twig', [
            'contact' => $contact,
        ]);
    }

    #[IsGranted('ROLE_EMPLOYE')]
    #[Route('/{id}/edit', name: 'app_contact_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Contact $contact, ContactRepository $contactRepo, ClientRepository $clientRepo): Response
    {
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contactRepo->save($contact, true);

            return $this->redirectToRoute('app_contact_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('contact/edit.html.twig', [
            'contact' => $contact,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_EMPLOYE')]
    #[Route('/{id}', name: 'app_contact_delete', methods: ['POST'])]
    public function delete(Request $request, Contact $contact, ContactRepository $contactRepo): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contact->getId(), $request->request->get('_token'))) {
            $contactRepo->remove($contact, true);
        }

        return $this->redirectToRoute('app_contact_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/contact/_delete_form.html.twig
<form method="post" action="{{ path('app_contact_delete', {'id': contact.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contact.id) }}">
    <button class="btn">Delete</button>
</form>

templates/contact/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/contact/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Contact{% endblock %}

{% block body %}
    <h1>Edit Contact</h1>

    {{ include('contact/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_contact_index') }}">back to list</a>

    {{ include('contact/_delete_form.html.twig') }}
{% endblock %}

templates/contact/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact index
{% endblock %}

{% block body %}
	<h1>Contact index</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Sender_firstname</th>
				<th>Sender_lastname</th>
				<th>Sender_email</th>
				<th>Subject</th>
				<th>Message</th>
				<th>Client</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for contact in contacts %}
				<tr>
					<td>{{ contact.id }}</td>
					<td>{{ contact.senderFirstname }}</td>
					<td>{{ contact.senderLastname }}</td>
					<td>{{ contact.senderEmail }}</td>
					<td>{{ contact.subject }}</td>
					<td>{{ contact.message }}</td>
					<td>{{ contact.client }}</td>
					<td>
						<a href="{{ path('app_contact_show', {'id': contact.id}) }}">show</a>
						<a href="{{ path('app_contact_edit', {'id': contact.id}) }}">edit</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="7">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('app_contact_new') }}">Create new</a>
{% endblock %}

templates/contact/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Contact{% endblock %}

{% block body %}
    <h1>Create new Contact</h1>

    {{ include('contact/_form.html.twig') }}

    <a href="{{ path('app_contact_index') }}">back to list</a>
{% endblock %}

templates/contact/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact
{% endblock %}

{% block body %}
	<h1>Contact</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ contact.id }}</td>
			</tr>
			<tr>
				<th>Sender_firstname</th>
				<td>{{ contact.senderFirstname }}</td>
			</tr>
			<tr>
				<th>Sender_lastname</th>
				<td>{{ contact.senderLastname }}</td>
			</tr>
			<tr>
				<th>Sender_email</th>
				<td>{{ contact.senderEmail }}</td>
			</tr>
			<tr>
				<th>Subject</th>
				<td>{{ contact.subject }}</td>
			</tr>
			<tr>
				<th>Message</th>
				<td>{{ contact.message }}</td>
			</tr>
			<tr>
				<th>Client</th>
				<td>{{ contact.client }}</td>
			</tr>
		</tbody>
	</table>

	<a href="{{ path('app_contact_index') }}">back to list</a>

	<a href="{{ path('app_contact_edit', {'id': contact.id}) }}">edit</a>

	{{ include('contact/_delete_form.html.twig') }}
{% endblock %}